# Generated by Django 3.1.12 on 2025-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.TextField()),
                ('assigned_ip', models.TextField()),
                ('dhcp_version', models.TextField()),
                ('lease_time', models.TextField()),
                ('lease_start', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
